#ifndef KN86_FONT_H
#define KN86_FONT_H

#include <stdint.h>

/* KN-86 Code Page (256 glyphs, 8x8 bitmap, MSB-first)
 * Auto-generated by tools/gen_font.py from Press Start 2P + CP437 + hand-drawn.
 */

extern const uint8_t kn86_font[256 * 8];

/* --- Custom-glyph extension (character-set.md §9, ADR-0036) -----------
 *
 * The 21 glyphs from the 2026-06-13 on-glass session: 4 KN-86 icons, an
 * 8-step vertical bar ramp (sparklines), and a 7-step horizontal sub-cell
 * bar set (fine progress bars). Codepoints + bitmaps are canonical per
 * character-set.md §9; the bitmaps live in font.c. */

/* KN-86 icons (0x10-0x13). */
#define KN86_GLYPH_ICON_CARTRIDGE  0x10
#define KN86_GLYPH_ICON_BATTERY    0x11
#define KN86_GLYPH_ICON_SIGNAL     0x12
#define KN86_GLYPH_ICON_PADLOCK    0x13

/* Vertical bar ramp 1/8..8/8 (0x96-0x9D); glyph = 0x96 + (k-1) for
 * k in 1..8. The 8/8 step (0x9D) duplicates full-block 0xA2 so the ramp
 * index stays closed. */
#define KN86_GLYPH_BAR_V_BASE      0x96   /* + (k-1), k in 1..8 */

/* Horizontal sub-cell bars, left-fill 1/8..7/8 (0xA8-0xAE); glyph =
 * 0xA7 + s for s in 1..7. The 8/8 case is full-block 0xA2. */
#define KN86_GLYPH_BAR_H_BASE      0xA8   /* + (s-1), s in 1..7 */

/* --- Status glyphs (four-channel rule, ui-design-language.md §4) ------
 *
 * The §4 status-icon vocabulary: running / starting / error / stopped.
 * character-set.md does NOT assign codepoints for these, so GWP-508
 * places them as follows:
 *   - RUNNING ('●') reuses the existing bullet glyph at 0x05.
 *   - STOPPED ('○') reuses the existing circle glyph at 0x06.
 *   - STARTING ('◐') and ERROR ('✖') are NEW bitmaps placed in the
 *     "remaining slots reserved for future symbols" tail of the
 *     0xF0-0xFF range (character-set.md §2): 0xF5 and 0xF6. */
#define KN86_GLYPH_STATUS_RUNNING   0x05  /* ● (existing bullet) */
#define KN86_GLYPH_STATUS_STOPPED   0x06  /* ○ (existing circle) */
#define KN86_GLYPH_STATUS_STARTING  0xF5  /* ◐ (GWP-508) */
#define KN86_GLYPH_STATUS_ERROR     0xF6  /* ✖ (GWP-508) */

#endif /* KN86_FONT_H */
